# Generated by Django 6.1.2 on 2026-10-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('summary', models.TextField(help_text='Short personal objective')),
                ('degree', models.CharField(max_length=100)),
                ('institute_name', models.CharField(max_length=150)),
                ('year_of_graduation', models.IntegerField()),
                ('company_name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=100)),
                ('years_of_experience', models.IntegerField()),
                ('skills', models.TextField(help_text='Comma-separated skills (e.g. Python, Django, SQL)')),
                ('hobbies', models.TextField(help_text='Comma-separated hobbies')),
                ('achievements', models.TextField(help_text='Comma-separated achievements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
